//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiseThink.NTCA.Web.FieldDirector {
    
    
    public partial class ViewTigerReserveDetails {
        
        /// <summary>
        /// imgbtnWord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomImageButton imgbtnWord;
        
        /// <summary>
        /// imgbtnPdf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomImageButton imgbtnPdf;
        
        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MainContent;
        
        /// <summary>
        /// APOCountSpan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl APOCountSpan;
        
        /// <summary>
        /// txtTigerReserve control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtTigerReserve;
        
        /// <summary>
        /// txtLegalStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtLegalStatus;
        
        /// <summary>
        /// txtCoreArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtCoreArea;
        
        /// <summary>
        /// txtCoreAreaVillageNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtCoreAreaVillageNumber;
        
        /// <summary>
        /// txtSettlementStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtSettlementStatus;
        
        /// <summary>
        /// txtTigerConservationPlan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtTigerConservationPlan;
        
        /// <summary>
        /// txtNameofPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtNameofPost;
        
        /// <summary>
        /// txtSanctionedStrength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtSanctionedStrength;
        
        /// <summary>
        /// txtStaffInPosition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtStaffInPosition;
        
        /// <summary>
        /// txtVacant control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtVacant;
        
        /// <summary>
        /// txtWildlifeTraining control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtWildlifeTraining;
        
        /// <summary>
        /// txtWildlifeTrainedStaff control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtWildlifeTrainedStaff;
        
        /// <summary>
        /// txtCasualothersStaff control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtCasualothersStaff;
        
        /// <summary>
        /// txtTypeOfWeaponsNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtTypeOfWeaponsNumber;
        
        /// <summary>
        /// txtShootingOfFilmsDocumentaries control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtShootingOfFilmsDocumentaries;
        
        /// <summary>
        /// txtAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtAddress;
        
        /// <summary>
        /// txtVehicleType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtVehicleType;
        
        /// <summary>
        /// txtWireless control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtWireless;
        
        /// <summary>
        /// txtBarriersDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtBarriersDetails;
        
        /// <summary>
        /// txtNumberOfBarriers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtNumberOfBarriers;
        
        /// <summary>
        /// txtBufferArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtBufferArea;
        
        /// <summary>
        /// txtDivisionArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtDivisionArea;
        
        /// <summary>
        /// txtSubDivisionArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtSubDivisionArea;
        
        /// <summary>
        /// txtRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtRange;
        
        /// <summary>
        /// txtBeats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtBeats;
        
        /// <summary>
        /// txtSections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtSections;
        
        /// <summary>
        /// txtAntiPoachingCampDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtAntiPoachingCampDetails;
        
        /// <summary>
        /// txtWatchTower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtWatchTower;
        
        /// <summary>
        /// txtNameAndTenureOfIncumbents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtNameAndTenureOfIncumbents;
        
        /// <summary>
        /// txtCaptiveElephants control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtCaptiveElephants;
        
        /// <summary>
        /// txtSpecialTigerProtectionForce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtSpecialTigerProtectionForce;
        
        /// <summary>
        /// txtSteeringCommitteeFoundationStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtSteeringCommitteeFoundationStatus;
        
        /// <summary>
        /// txtTigerConservationFoundation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtTigerConservationFoundation;
        
        /// <summary>
        /// txtTotalArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtTotalArea;
        
        /// <summary>
        /// txtWildlifeOtherInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtWildlifeOtherInformation;
        
        /// <summary>
        /// txtEstimationReportForLast3Years control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtEstimationReportForLast3Years;
        
        /// <summary>
        /// txtImportantSpeciesAnimalsFoundInTR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtImportantSpeciesAnimalsFoundInTR;
        
        /// <summary>
        /// txtWildlifePopulationEstimates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtWildlifePopulationEstimates;
        
        /// <summary>
        /// txtDeathOfAnimals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtDeathOfAnimals;
        
        /// <summary>
        /// txtFirelines control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtFirelines;
        
        /// <summary>
        /// txtForestType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtForestType;
        
        /// <summary>
        /// txtAnyotherImportantWildlifeInformationUntilLastYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtAnyotherImportantWildlifeInformationUntilLastYear;
        
        /// <summary>
        /// txtRevenueGeneratedInLast5YearsTourism control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtRevenueGeneratedInLast5YearsTourism;
        
        /// <summary>
        /// txtRevenueGeneratedInLast5YearsOthers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtRevenueGeneratedInLast5YearsOthers;
        
        /// <summary>
        /// txtAnnualNoOfTourists control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtAnnualNoOfTourists;
        
        /// <summary>
        /// txtFundsProvidedUnderStatePlanInLast5Years control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtFundsProvidedUnderStatePlanInLast5Years;
        
        /// <summary>
        /// txtFundsFromCAMPAandOtherResources control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtFundsFromCAMPAandOtherResources;
        
        /// <summary>
        /// txtFundsProvidedByCSSPT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtFundsProvidedByCSSPT;
        
        /// <summary>
        /// txtExGratiaPaidInLast5Years control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtExGratiaPaidInLast5Years;
        
        /// <summary>
        /// txtCropDamage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtCropDamage;
        
        /// <summary>
        /// txtAnyOtherImportantFinancialCWWInformationUntilLastYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WiseThink.CustomLabel txtAnyOtherImportantFinancialCWWInformationUntilLastYear;
    }
}
